In [1]:
pip install numpy

     ---------------------------------------- 0.0/59.7 kB ? eta -:--:--
     ------------- ------------------------ 20.5/59.7 kB 217.9 kB/s eta 0:00:01
     -------------------------------------- 59.7/59.7 kB 526.6 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
    --------------------------------------- 0.2/12.9 MB 5.3 MB/s eta 0:00:03
   --- ------------------------------------ 1.0/12.9 MB 12.5 MB/s eta 0:00:01
   ----- ---------------------------------- 1.7/12.9 MB 13.3 MB/s eta 0:00:01
   ------- -------------------------------- 2.5/12.9 MB 14.8 MB/s eta 0:00:01
   ---------- ----------------------------- 3.5/12.9 MB 16.2 MB/s eta 0:00:01
   -------------- ------------------------- 4.6/12.9 MB 17.2 MB/s eta 0:00:01
   ----------------- ---------------------- 5.6/12.9 MB 18.0 MB/s eta 0:00:01
   --------------------- ------------------ 6.8/12.9 MB 19.0 MB/s eta 0:00:01
   ----------------------- ---------------- 7.6/12.9 MB 18.8 MB/s eta 0:00:


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: C:\Users\dhana\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [9]:
array_a = np.array([1,2,3,4])

In [11]:
type(array_a)

numpy.ndarray

In [10]:
print(array_a)

[1 2 3 4]


In [5]:
print([1,2,3,4])

[1, 2, 3, 4]


In [6]:
print([1,2,3,4,"Dhananjay"])

[1, 2, 3, 4, 'Dhananjay']


In [7]:
array_A= np.array([1,2,3,4,5,"Dhananajay"])

In [8]:
array_A

array(['1', '2', '3', '4', '5', 'Dhananajay'], dtype='<U21')

In [12]:
type(array_A)

numpy.ndarray

In [13]:
print(array_a.shape)

(4,)


In [14]:
array_b = np.array([[1,2,3,4,5],[1,2,3,4,5]])

In [16]:
print(array_b)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [21]:
array_b.shape

(2, 5)

In [22]:
## 3 x 3

In [45]:
seq_a = [1,2,3]
seq_b = [4,5,6]
seq_c = [7,8,9]
seq_d = [10.5,11.0,12]

array_abc = np.array([seq_a,seq_b,seq_c,seq_d])

In [46]:
type(array_abc)

numpy.ndarray

In [47]:
array_abc.shape

(4, 3)

In [48]:
array_abc

array([[ 1. ,  2. ,  3. ],
       [ 4. ,  5. ,  6. ],
       [ 7. ,  8. ,  9. ],
       [10.5, 11. , 12. ]])

In [49]:
## Numpy - Indexing 

In [59]:
array_a = np.array([[1,2,3],[4,5,6]])
print(array_a.shape)

(2, 3)


In [60]:
array_a.size

6

In [61]:
array_b = array_a.reshape(3,2,)

In [62]:
array_b.shape

(3, 2)

In [63]:
array_b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [69]:
print(array_b[0])

[1 2]


In [68]:
print(array_b[:,1])

[2 4 6]


In [71]:
print(array_b[0,0])

1


In [56]:
array_b = array_a.reshape(6,1)

In [57]:
array_b.shape

(6, 1)

In [58]:
array_b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [72]:
# numpy reshaping and indexing

In [73]:
array_a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [74]:
array_a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [77]:
array_b =array_a.reshape(1,16)

In [78]:
array_b = array_a.T

In [79]:
array_b

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [81]:
array_A = np.array([[1,2,3],[4,5,6]],dtype = float)
print(array_A)

[[1. 2. 3.]
 [4. 5. 6.]]


In [83]:
array_b = np.zeros((3,3))
print(array_b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [85]:
array_c = np.ones((3,3),dtype = int)
print(array_c)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [86]:
array_d = np.full((3,3),5)

In [87]:
array_d

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [88]:
array_e = np.random.random((3,4))
print(array_e)

[[0.27610737 0.51989126 0.11802371 0.72072366]
 [0.53481402 0.31327413 0.86898598 0.70176227]
 [0.42434263 0.64744753 0.47960317 0.18445108]]


In [89]:
# Default array type

In [93]:
# np.int16 Integer (-32768 to 32767)
array_a = np.array([32766,32767,32768],dtype = np.int16)
array_a.dtype

OverflowError: Python integer 32768 out of bounds for int16

In [96]:
# np.int32 Integer (-2147483648 to 2147483647)

In [100]:
# np.uint16 Unsiged integer (0 to 65535)
# np.unint64 unsigned integer (0 to 4294967295)
# np.unsigned integer (0 to 1844744073709551615)

array_b = np.array([-1,0,1],dtype=np.uint16)

OverflowError: Python integer -1 out of bounds for uint16

In [102]:
array_b = np.array([1,0,1],dtype=np.uint16)
array_b

array([1, 0, 1], dtype=uint16)

In [103]:
row_1 = [1,2,3,4,5]
row_2 = [6,7,8,9,10]
row_3 = [11,12,13,14,15]
row_4 = [16,17,18,19,20]
row_5 = [21,22,23,24,25]

test_data = np.array([row_1,row_2,row_3,row_4,row_5])

In [104]:
print(test_data)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [105]:
# Slice

In [106]:
#print 3 rd and 4 th column of every row

In [114]:
test_data[:,2:4:1,]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24]])

In [115]:
# using negative indexing

In [119]:
test_data[:,-2:-4:-1]

array([[ 4,  3],
       [ 9,  8],
       [14, 13],
       [19, 18],
       [24, 23]])

In [120]:
# boolean 

In [121]:
greater_than_five = test_data >5
print(greater_than_five)

[[False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [122]:
test_data[greater_than_five]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25])

In [123]:
# where

In [124]:
drop_under_5_array = np.where(test_data > 5, test_data, 0)
print(drop_under_5_array)

[[ 0  0  0  0  0]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [125]:
# logical_and

In [127]:
drop_under_5_and_over_20 = np.logical_and(test_data>5 , test_data<20)

In [128]:
drop_under_5_and_over_20

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [False, False, False, False, False]])

In [129]:
# advance-indexing-array

In [132]:
array = np.arange(0,100,5)
print(array)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [133]:
array.shape

(20,)

In [135]:
array = array.reshape(4,5)

In [136]:
array

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [138]:
print(array[:,-1])

[20 45 70 95]


In [141]:
array_above_50 = array[array>=50]

In [142]:
array_above_50

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [150]:
print(np.where(array>=50,array*2,0))

[[  0   0   0   0   0]
 [  0   0   0   0   0]
 [100 110 120 130 140]
 [150 160 170 180 190]]


In [146]:
print(array_above_50[0:len(array_above_50):2])

[50 60 70 80 90]


In [151]:
# array-math_lesson

In [175]:
array_a = np.array([[1,2],[3,4]])
array_b = np.array([[2,2],[6,6]])

In [164]:
#single array array operation

# axis =0   ----> along column

#axis =1    ----> along row

In [165]:
print(array_a.sum(axis=0))

[4 6]


In [166]:
print(array_b.sum(axis=1))

[ 4 12  9]


In [167]:
print(array_a.cumsum())

[ 1  3  6 10]


In [172]:
print(array_a.prod())

24


In [173]:
print(array_a.cumprod())

[ 1  2  6 24]


In [176]:
# two array math

In [177]:
print(array_a + array_b)

[[ 3  4]
 [ 9 10]]


In [178]:
print(array_a - array_b)

[[-1  0]
 [-3 -2]]


In [179]:
print(array_a * array_b)

[[ 2  4]
 [18 24]]


In [183]:
print((array_a / array_b))

[[0.5        1.        ]
 [0.5        0.66666667]]


In [184]:
print(np.dot(array_a,array_b))

[[14 14]
 [30 30]]


In [187]:
array_a = np.array([[1,2,3],[4,5,6],[7,8,9]])
array_b = np.array([[2,2,2],[3,4,5],[6,7,8]])
print(array_a)
print("---------------------------------------")
print(array_b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------------------------------
[[2 2 2]
 [3 4 5]
 [6 7 8]]


In [190]:
print(array_a.sum(axis = 0))

[12 15 18]


In [191]:
#print(array_a.ptp(axis=1))

AttributeError: `ptp` was removed from the ndarray class in NumPy 2.0. Use np.ptp(arr, ...) instead.

In [192]:
print(array_a.min())

1


In [193]:
print(array_a.max())

9


In [194]:
print(array_a.mean())

5.0


In [195]:
print(array_a.min(axis=1))
print(array_a.max(axis=1))
print(array_a.mean(axis=1))

[1 4 7]
[3 6 9]
[2. 5. 8.]


In [196]:
print(array_a.min(axis=0))
print(array_a.max(axis=0))
print(array_a.mean(axis=0))

[1 2 3]
[7 8 9]
[4. 5. 6.]


In [197]:
print(np.power(array_a,array_b))

[[       1        4        9]
 [      64      625     7776]
 [  117649  2097152 43046721]]


In [198]:
array_c = np.array([[1,1,1],[2,2,2],[3,3,3]])

In [199]:
print(array_a + array_b + array_c)

[[ 4  5  6]
 [ 9 11 13]
 [16 18 20]]


In [200]:
print(array_a / array_b / array_c)

[[0.5        1.         1.5       ]
 [0.66666667 0.625      0.6       ]
 [0.38888889 0.38095238 0.375     ]]


In [201]:
# numpy broadcasting

In [208]:
array_a = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
array_b = np.array([0,1,2,3])
array_c = np.array([[1],[2],[3]])
array_d = np.array([[0,1,2,3],[0,1,2,3],[0,1,2,3]])

In [205]:
print(array_a + array_b)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [209]:
print(array_d+array_a)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
