# load the numpy library

In [10]:
import numpy as np

# The Basic

In [11]:
a = np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [12]:
b =np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [13]:
a.ndim

1

In [14]:
# get shape
b.shape

(2, 3)

In [15]:
# get type
a.dtype

dtype('int16')

In [16]:
b.dtype

dtype('float64')

In [24]:
# get size
print(a.itemsize)
print(b.itemsize)

4
8


In [25]:
a = np.array([1,2,3],dtype='int32')
print(a.itemsize)
print(b.itemsize)

4
8


In [26]:
# get total size
print(a.size*a.itemsize)
print(b.size*b.itemsize)

12
48


In [27]:
a.nbytes

12

In [28]:
b.nbytes

48

# Accsssing/Changing specific elements,rows,columns etc

In [33]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [32]:
a = np.arange(1,15).reshape(2,7)
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [34]:
a.shape

(2, 7)

In [37]:
# get a specific elements [r,c]
# get element 13
print(a[1,5])
print(a[1,-2])

13
13


In [39]:
# get a specific row
print(a[0,:])

[1 2 3 4 5 6 7]


In [41]:
# get a specific column1
print(a[:,1])

[2 9]


In [45]:
# getting a little more fancy[startindex:endindex:stepsize] 2,4,6
print(a[0,1:6:2])
print(a[0,1:-1:2])

[2 4 6]
[2 4 6]


In [46]:
a[1,5] = 20

In [47]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [48]:
# make all element of column2 10
a[:,2]=10
print(a)

[[ 1  2 10  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [49]:
# make element of column2 1 ,2
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [52]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [54]:
# Get specific element (work outside in) 4
print(b[0,1,1])

4


In [69]:
#replace
b[:,1,:]=[[9,9,],[8,8]]

In [67]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initialize Different Type of Arrays

In [71]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [78]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [82]:
# all is matrix
np.ones((4,3,3),dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [89]:
# Any other number
np.full((2,2),99,dtype='int16')

array([[99, 99],
       [99, 99]], dtype=int16)

In [91]:
a = np.arange(1,15).reshape(2,7)
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [92]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [94]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [102]:
# Random decimal numbers
np.random.rand(4,2,2)

array([[[0.08529189, 0.29987008],
        [0.01171622, 0.66512342]],

       [[0.91124488, 0.5079907 ],
        [0.84241043, 0.49689714]],

       [[0.12858078, 0.65876117],
        [0.08574445, 0.26219624]],

       [[0.37170327, 0.90409686],
        [0.65034726, 0.34732778]]])

In [103]:
np.random.random_sample(a.shape)

array([[0.27855336, 0.09312824, 0.87240074, 0.67238582, 0.82485185,
        0.91259123, 0.33925636],
       [0.0162135 , 0.7193821 , 0.04743908, 0.12966014, 0.8170395 ,
        0.95444181, 0.79349487]])

In [104]:
np.random.uniform(low =5, high=10,size=(2,5))

array([[7.87121237, 8.6332962 , 7.0730098 , 5.12263464, 9.38262385],
       [9.47432282, 5.52408938, 7.49662908, 5.70804141, 9.9846025 ]])

In [122]:
np.random.randint(1,7,size=(3,3))

array([[3, 2, 2],
       [2, 6, 5],
       [4, 1, 5]], dtype=int32)

In [123]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [134]:
arr = np.array([1,2,3])
r1 = np.hstack((np.repeat(arr,3),np.tile([1,2,3],2)))
print(r1)
print(np.hstack((np.repeat(arr, 3), np.tile([1, 2, 3], 2))))

r1 = np.concatenate((np.repeat(arr, 3), np.tile([1, 2, 3], 3)))

print(r1)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [128]:
np.tile(arr,2)

array([1, 2, 3, 1, 2, 3])

In [139]:
output = np.ones((5,5))
print(output)
print("---------------------------")
z = np.zeros((3,3))
print(z)
print("---------------------------")
z[1,1]=9
print(z)
print("----------------------------")
output[1:4,1:4]=z
print(output)
print("----------------------------")
output[1:-1,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
---------------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
---------------------------
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
----------------------------
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
----------------------------
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be craeful when copying arrays!!

In [140]:
a= [1,2,3]
b=a
b[0] = 100
print("b:",b)
print("a:",a)

b: [100, 2, 3]
a: [100, 2, 3]


In [141]:
a= [1,2,3]
b=a.copy()
b[0]=100
print("b:",b)
print("a:",a)

b: [100, 2, 3]
a: [1, 2, 3]


# Mathematics

In [166]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [167]:
a+2
a

array([1, 2, 3, 4])

In [168]:
a*2

array([2, 4, 6, 8])

In [169]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [170]:
b= np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [171]:
a**2

array([ 1,  4,  9, 16])

In [173]:
# take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [178]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
#https://numpy.org/doc/stable/reference/routines.math.html

## Linear Algebra

In [182]:
a = np.ones((2,3))
print(a)
print("----------------------------")
b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
----------------------------
[[2 2]
 [2 2]
 [2 2]]


In [183]:
np.dot(a,b)

array([[6., 6.],
       [6., 6.]])

In [184]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [186]:
# find the determinant
c= np.identity(3)
print(np.linalg.det(c))

1.0


In [187]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

# Statistics

In [189]:
stats = np.array([[1,2,3,4],[5,6,7,8]])
stats

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [190]:
np.min(stats)

np.int64(1)

In [191]:
np.max(stats)

np.int64(8)

In [192]:
np.mean(stats)

np.float64(4.5)

In [196]:
np.max(stats,axis=0)

array([5, 6, 7, 8])

In [197]:
np.max(stats,axis=1)

array([4, 8])

In [198]:
np.mean(stats,axis=1)

array([2.5, 6.5])

In [200]:
np.sum(stats,axis=0)

array([ 6,  8, 10, 12])

# Reorganizing arrays

In [208]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)
print("-----------------------------")
after = before.reshape(2,2,2)
print(after)
print("-----------------------------")
after = before.reshape(4,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
-----------------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
-----------------------------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [210]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [214]:
# horizontal stack

In [216]:
h1=np.ones((2,4))
h2=np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscelleaneous 
Load Data from file

In [223]:
file_data = np.genfromtxt('data.txt',delimiter=',')

In [224]:
file_data = file_data.astype('int32')
file_data

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

# Bollean Masking and Advance Indexing

In [226]:
file_data[file_data >50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [227]:
# you can index witg a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [234]:
file_data = np.genfromtxt('data.txt',delimiter=',')
file_data = file_data.astype('int32')
file_data

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

In [235]:
np.any(file_data>50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [237]:
np.all(file_data>50,axis=1)

array([False, False, False])

In [240]:
((file_data>50) & (file_data<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [241]:
(~((file_data>50) & (file_data<100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [246]:
a = np.arange(1,31).reshape(6,5)

In [247]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

# [[11,12],
#  [16,17]]

In [249]:
a[2:4,0:2]

array([[11, 12],
       [16, 17]])

# 2,8,14,20

In [250]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

# [4,5]

# [[24,25],
# [29,30]]

In [256]:
a[0,3:5]

array([4, 5])

In [257]:
a[4:6,3:5]

array([[24, 25],
       [29, 30]])

In [258]:
a[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])