# 101 NumPy Exercises for Data Analysis (Python)


1. Import numpy as np and see the version

In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.1.2


2. How to Create a 1D array of numbers from 0 to 9

Desired output:

 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])e a 1D array?


In [6]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. Create a 3×3 numpy array of all True’s

In [9]:
np.full((3,3),True,dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [10]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4 . Extract all odd numbers from arr

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired output:

 array([1, 3, 5, 7, 9])


In [20]:
arr = np.arange(0, 10).tolist()
arr = [i for i in arr if i % 2 != 0]
print(arr)

[1, 3, 5, 7, 9]


In [22]:
arr = np.arange(0,10).tolist()
arr =[i for i in arr if i%2==1]
print(np.array(arr))

[1 3 5 7 9]


5. How to replace items that satisfy a condition with another value in numpy array?

Difficulty Level: L1

Q. Replace all odd numbers in arr with -1

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:

#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [28]:
arr = np.arange(0,10).tolist()
for i in range(len(arr)):
    if arr[i]%2==1:
        arr[i]=-1
arr = np.array(arr)        
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [32]:
arr = np.arange(0,10)
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


6. How to replace items that satisfy a condition without affecting the original array?

Difficulty Level: L2

Q. Replace all odd numbers in arr with -1 without changing arr

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:

out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [36]:
arr = np.arange(0,10)
arr = np.where(arr%2==1,-1,arr)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


7. How to reshape an array?

Difficulty Level: L1

Q. Convert a 1D array to a 2D array with 2 rows

Input:

np.arange(10)

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:

#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])

In [45]:
arr = np.arange(10)
#print(arr)
arr1 = np.reshape(arr,(2,5))
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

8. How to stack two arrays vertically?

Difficulty Level: L2

Q. Stack arrays a and b vertically

Input

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

Desired Output:

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])


In [54]:
a = np.arange(0,10).reshape(2,5)
b = np.repeat(1,10).reshape(2,5)
print(a)
print("-----------------")
print(b)
print("-----------------")
arr = np.concatenate([a,b],axis=0)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]
-----------------
[[1 1 1 1 1]
 [1 1 1 1 1]]
-----------------
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [55]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [57]:
np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

9. How to stack two arrays horizontally?

Difficulty Level: L2

Q. Stack the arrays a and b horizontally.

Input

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

Desired Output:

#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])


In [59]:
a = np.arange(0,10).reshape(2,5)
b = np.repeat(1,10).reshape(2,5)
print(a)
print("______________________")
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
______________________
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [61]:
#method 1
np.concatenate([a,b],axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [62]:
# method 2
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [63]:
# method 3
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

10. How to generate custom sequences in numpy without hardcoding?

Difficulty Level: L2

Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

a = np.array([1,2,3])`

Desired Output:

#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


In [64]:
a = np.array([1,2,3])

In [66]:
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

11. How to get the common items between two python numpy arrays?

Difficulty Level: L2

Q. Get the common items between a and b

Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

Desired Output:

array([2, 4])


In [69]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


12. How to remove from one array those items that exist in another?

Difficulty Level: L2

Q. From array a remove all items present in array b

Input:

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

Desired Output:

array([1,2,3,4])

In [71]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

13. How to get the positions where elements of two arrays match?

Difficulty Level: L2

Q. Get the positions where elements of a and b match

Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

Desired Output:

#> (array([1, 3, 5, 7]),)

In [75]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7]),)

14. How to extract all numbers between a given range from a numpy array?

Difficulty Level: L2

Q. Get all items between 5 and 10 from a.

Input:

a = np.array([2, 6, 1, 9, 10, 3, 27])

Desired Output:

(array([6, 9, 10]),)

In [80]:
# method 1
a = np.array([2, 6, 1, 9, 10, 3, 27])
a = a[np.logical_and(a >= 5,a <= 10)]
a

array([ 6,  9, 10])

In [81]:
# method2
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])

In [82]:
# method3
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

15. How to make a python function that handles scalars to work on numpy arrays?

Difficulty Level: L2

Q. Convert the function maxx that works on two scalars, to work on two arrays.

Input:

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5

Desired Output:

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

In [83]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

16. How to swap two columns in a 2d numpy array?

Difficulty Level: L2

Q. Swap columns 1 and 2 in the array arr.

arr = np.arange(9).reshape(3,3)
arr

In [88]:
arr = np.arange(9).reshape(3,3)
arr
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

17. How to swap two rows in a 2d numpy array?

Difficulty Level: L2

Q. Swap rows 1 and 2 in the array arr:

arr = np.arange(9).reshape(3,3)
arr

In [91]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[[0,2,1],:]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

18. How to reverse the rows of a 2D array?

Difficulty Level: L2

Q. Reverse the rows of a 2D array arr.

 Input
arr = np.arange(9).reshape(3,3)

In [96]:
arr = np.arange(0,9).reshape(3,3)
print(arr)
arr[::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

19. How to reverse the columns of a 2D array?

Difficulty Level: L2

Q. Reverse the columns of a 2D array arr.

Input
arr = np.arange(9).reshape(3,3)

In [98]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:,::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

20. How to create a 2D array containing random floats between 5 and 10?

Difficulty Level: L2

Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
Show Solution

Input
arr = np.arange(9).reshape(3,3)

In [115]:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
rand_arr

array([[6.3544194 , 8.66763846, 7.0432916 ],
       [7.02484376, 7.69983041, 5.2867745 ],
       [9.2767544 , 8.70645335, 9.50160802],
       [8.61586287, 9.64371114, 5.21605207],
       [7.294257  , 6.08527444, 7.63541412]])

In [111]:
rand_arr = np.random.uniform(low =5,high =10,size=(5,3))
rand_arr

array([[8.82727228, 6.72691612, 8.49347717],
       [5.73584704, 7.10959613, 6.83626114],
       [9.03250394, 9.60217421, 8.77678574],
       [7.03744423, 5.28662842, 5.63836214],
       [8.25632321, 5.10049241, 6.11012446]])

21. How to print only 3 decimal places in python numpy array?

Difficulty Level: L1

Q. Print or show only 3 decimal places of the numpy array rand_arr.

Input:

rand_arr = np.random.random((5,3))


In [119]:
rand_arr = np.random.uniform(low =5,high =10,size=(5,3))
rand_arr

array([[6.8551714 , 6.34756466, 9.30557312],
       [8.85695214, 8.48470045, 6.62868494],
       [5.12014259, 5.43057462, 8.05270769],
       [7.80018127, 5.25933449, 9.361196  ],
       [8.35044668, 9.91325643, 5.70383989]])

In [121]:
np.set_printoptions(precision=3)
rand_arr[:,:]

array([[6.855, 6.348, 9.306],
       [8.857, 8.485, 6.629],
       [5.12 , 5.431, 8.053],
       [7.8  , 5.259, 9.361],
       [8.35 , 9.913, 5.704]])

22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

Difficulty Level: L1

Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

Input:

Create the random array
#> array([[  5.434049e-04,   2.783694e-04,   4.245176e-04],
#>        [  8.447761e-04,   4.718856e-06,   1.215691e-04],
#>        [  6.707491e-04,   8.258528e-04,   1.367066e-04]])

Desired Output:

#> array([[ 0.000543,  0.000278,  0.000425],
#>        [ 0.000845,  0.000005,  0.000122],
#>        [ 0.000671,  0.000826,  0.000137]])

In [128]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr
np.set_printoptions(suppress=True,precision=10)


In [129]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[0.0005434049, 0.0002783694, 0.0004245176],
       [0.0008447761, 0.0000047189, 0.0001215691],
       [0.0006707491, 0.0008258528, 0.0001367066]])

23. How to limit the number of items printed in output of numpy array?

Difficulty Level: L1

Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.

Input:

a = np.arange(15)
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Desired Output:

#> array([ 0,  1,  2, ..., 12, 13, 14])


24. How to print the full numpy array without truncating

Difficulty Level: L1

Q. Print the full numpy array a without truncating.

Input:

np.set_printoptions(threshold=6)
a = np.arange(15)
a
#> array([ 0,  1,  2, ..., 12, 13, 14])

Desired Output:

a
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])


In [144]:
a=np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [135]:
arr = np.arange(15)
print(arr)
np.set_printoptions(threshold=10)
arr = np.arange(15)
arr

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([ 0,  1,  2, ..., 12, 13, 14])

25. How to import a dataset with numbers and texts keeping the text intact in python numpy?

Difficulty Level: L2

Q. Import the iris dataset keeping the text intact.

In [140]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
print(iris[0:10,:])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 ...
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [ ]:
26. How to extract a particular column from 1D array of tuples?

Difficulty Level: L2

Q. Extract the text column species from the 1D iris imported in previous question.

Input:

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
